### ISSUE TITLE
2 массива

### ISSUE THREAD

**Issue by casa7x** [Tatsianazhylevich/Lesson-14#2]
https://github.com/Tatsianazhylevich/Lesson-14/blob/f63b6049aeaeba8d44e29e9f508d3df5c2e5b9d8/script.js#L56

В этой задаче, надо разделить на 2 разных массива - взрослых и детей и потом уже работать с этим массивами, для определений детей у взрослых. Профессию можно на этапе разделения узнавать

**Comment by Tatsianazhylevich** [comment]
Разделила на 2 новых массива и детей назначала уже исходя из данных этих массивов
